import Head from "next/head";
import About from "../components/About";
import Contact_me from "../components/Contact_me";
import WorkExperience from "../components/WorkExperience";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Projects from "../components/Projects";
import Skills from "../components/Skills";
import Link from "next/link";
import { Experience, PageInfo, Project, Skill, Social } from "../typings";
import { GetStaticProps, NextPage } from "next";
import { fetchSkills } from "../utils/fetchSkills";
import { fetchSocials } from "../utils/fetchSocials";
import { fetchPageInfo } from "../utils/fetchPageInfo";
import { fetchExperiences } from "../utils/fetchExperiences";
import { fetchProjects } from "../utils/fetchProjects";

type Props = {
  pageInfo: PageInfo;
  experiences: Experience[];
  projects: Project[];
  skills: Skill[];
  socials: Social[];
};

const Home = ({ pageInfo, experiences, projects, skills, socials }: Props) => {
  //console.log(pageInfo);
  return (
    <div
      className='bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll 
    overflow-x-hidden z-0 scrollbar-thin scrollbar-track-gray-400/20 scrollbar-thumb-[#cbd5e1]/80 
    scrollbar-thumb-rounded-md'
    >
      <Head>
        <title>Oluwatosin Daniel | Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.jpg' />
      </Head>
      <Header socials={socials} />
      <section className='snap-start' id='hero'>
        <Hero pageInfo={pageInfo} />
      </section>
      <section className='snap-center' id='about'>
        <About pageInfo={pageInfo} />
      </section>
      <section className='snap-center' id='experience'>
        <WorkExperience experiences={experiences} />
      </section>
      <section className='snap-start' id='skills'>
        <Skills skills={skills} />
      </section>
      <section className='snap-start' id='projects'>
        <Projects projects={projects} />
      </section>
      <section className='snap-start' id='contact'>
        <Contact_me pageInfo={pageInfo} />
      </section>
      <Link href='#hero'>
        <footer className='absolute bottom-5 right-10 cursor-pointer'>
          <div className='flex items-center justify-center'>
            <img
              className='h-10 w-10 rounded-full filter grayscale hover:grayscale-0 cursor-pointer'
              // src='https://i.imgur.com/e2yvD6A.png'
              src='/assets/logo.jpg'
              alt=''
            />
          </div>
        </footer>
      </Link>
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps<Props> = async () => {
  const pageInfo: PageInfo = await fetchPageInfo();
  const experiences: Experience[] = (await fetchExperiences()) ?? [];
  const projects: Project[] = (await fetchProjects()) ?? [];
  const skills: Skill[] = (await fetchSkills()) ?? [];
  const socials: Social[] = (await fetchSocials()) ?? [];

  return {
    props: {
      pageInfo,
      experiences,
      projects,
      skills,
      socials,
    },
    // Next.js will attempt to re-generate the props:
    // - When a request come in
    // - At most once every 10 seconds
    revalidate: 10,
  };
};
